# Generated by Django 3.2.7 on 2024-02-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0002_staff_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('user_type', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
    ]
