# Generated by Django 3.2.7 on 2024-02-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0003_tbl_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(max_length=150)),
                ('flight_model', models.CharField(max_length=150)),
                ('flight_maxcap', models.CharField(max_length=150)),
                ('business_cap', models.CharField(max_length=150)),
                ('first_cap', models.CharField(max_length=150)),
                ('economy_cap', models.CharField(max_length=150)),
                ('year', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
    ]
