# Generated by Django 3.2.7 on 2024-02-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0004_tbl_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_point', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('distance', models.CharField(max_length=150)),
            ],
        ),
    ]
