# Generated by Django 3.2.7 on 2024-02-13 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0005_tbl_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_routeassign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('first_class_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('business_class_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('normal_class_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('infant_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=150)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.tbl_flight')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.tbl_route')),
            ],
        ),
    ]
