# Generated by Django 3.2.7 on 2024-02-15 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0006_tbl_routeassign'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_bookingmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_traveller_no', models.CharField(max_length=150)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=150)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.customer_reg')),
                ('routeassign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.tbl_routeassign')),
            ],
        ),
    ]
