# Generated by Django 3.2.7 on 2024-02-15 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0007_tbl_bookingmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_bookingchild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=150)),
                ('lname', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=150)),
                ('idproof_no', models.CharField(max_length=150)),
                ('bookingmaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.tbl_bookingmaster')),
            ],
        ),
    ]
