# Generated by Django 3.2.7 on 2024-02-16 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0008_tbl_bookingchild'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amt', models.CharField(max_length=150)),
                ('card_no', models.CharField(max_length=150)),
                ('card_name', models.CharField(max_length=150)),
                ('card_type', models.CharField(max_length=150)),
                ('cvv', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('bookingmaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.tbl_bookingmaster')),
            ],
        ),
    ]
