# Generated by Django 3.2.7 on 2024-03-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0009_tbl_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_route',
            name='stop',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
