# Generated by Django 3.2.7 on 2026-01-01 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0010_tbl_route_stop'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_luggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('status', models.CharField(default='Added', max_length=150)),
                ('bookingmaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.tbl_bookingmaster')),
            ],
        ),
    ]
