# Generated by Django 3.2.7 on 2026-01-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0011_tbl_luggage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_luggage',
            old_name='weight',
            new_name='total_weight',
        ),
        migrations.AddField(
            model_name='tbl_luggage',
            name='num_baggage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
