# Generated by Django 3.2.7 on 2026-01-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0012_auto_20260102_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150)),
                ('condition', models.CharField(max_length=150)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
